name: Check Pull-Request

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.3.0
        bundler-cache: true
    - run: bundle install
    - run: ./bin/rails db:create db:migrate
    - run: ./bin/rails test:all
